# Define the name of the workflow
name: Release PyPi Package

# Only run on pull request merges
on:
  push:
    branches:
      - fix-PyPi-releases
      
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # Install dependencies required for building and publishing the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      # Build the package
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      # Publish the package to PyPI
      - name: Publish package
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload dist/*
